### ISSUE TITLE
Missing Resources:

### ISSUE THREAD

**Issue by ChronoHELP** [TheSph1nx/SLICKERMASTER-REV4#3]
Couple of missing PNG's
![image](https://user-images.githubusercontent.com/53595766/62416182-d9fe7580-b603-11e9-917a-840fa72cc71e.png)

**Comment by ChronoHELP** [comment]
http://prntscr.com/onyha0

**Comment by TheSph1nx** [comment]
Added the files, sorry about that, github upload fault
